"""Core modules for xplain CLI."""

from .copilot import (
    ask_copilot,
    explain_command,
    explain_error,
    explain_code,
    explain_diff,
    explain_auto,
    chat_with_copilot,
    get_backend,
    set_model,
    set_tldr_mode,
    is_tldr_mode,
    CopilotCLIError,
    CopilotNotFoundError,
    BackendNotAvailableError,
    check_copilot_installed,
)

from .formatter import (
    console,
    print_banner,
    print_explanation,
    print_command,
    print_code,
    print_error,
    print_warning,
    print_success,
    print_info,
    LoadingSpinner,
    format_language_flag,
    detect_code_language,
    set_output_file,
    export_explanation,
)

__all__ = [
    # Copilot
    "ask_copilot",
    "explain_command",
    "explain_error",
    "explain_code",
    "explain_diff",
    "explain_auto",
    "chat_with_copilot",
    "get_backend",
    "set_model",
    "set_tldr_mode",
    "is_tldr_mode",
    "CopilotCLIError",
    "CopilotNotFoundError",
    "BackendNotAvailableError",
    "check_copilot_installed",
    # Formatter
    "console",
    "print_banner",
    "print_explanation",
    "print_command",
    "print_code",
    "print_error",
    "print_warning",
    "print_success",
    "print_info",
    "LoadingSpinner",
    "format_language_flag",
    "detect_code_language",
    "set_output_file",
    "export_explanation",
]
